//! Artifact cache behaviour and PTX helpers (no compiler needed).

use launchbound_build::{ArtifactCache, entry_param_count, extract_ptx};

const FAKE_PTX: &str = "\
// Generated by LLVM NVPTX Back-End
.version 7.0
.target sm_80
.address_size 64

.visible .entry reduce(
\t.param .u64 .ptr .align 1 reduce_param_0,
\t.param .u64 reduce_param_1,
\t.param .u64 .ptr .align 1 reduce_param_2,
\t.param .u64 reduce_param_3
)
{
\tret;
}
";

#[test]
fn cache_stores_and_hits() {
    let dir = std::env::temp_dir().join(format!("lb-cache-test-{}", std::process::id()));
    let cache = ArtifactCache::new(dir.clone());
    assert!(cache.lookup("k", "abc123").is_none());
    let path = cache.store("k", "abc123", FAKE_PTX).unwrap();
    assert_eq!(cache.lookup("k", "abc123"), Some(path.clone()));
    assert_eq!(std::fs::read_to_string(path).unwrap(), FAKE_PTX);
    std::fs::remove_dir_all(dir).ok();
}

#[test]
fn extracts_ptx_from_mixed_build_output() {
    let noisy = format!("Building rustc backend...\nCompiling...\n{FAKE_PTX}");
    let ptx = extract_ptx(&noisy).unwrap();
    assert!(ptx.starts_with("// Generated by LLVM NVPTX Back-End"));
    assert!(ptx.contains(".entry reduce("));
    assert!(extract_ptx("no ptx here at all").is_none());
}

#[test]
fn counts_entry_params() {
    assert_eq!(entry_param_count(FAKE_PTX, "reduce"), Some(4));
    assert_eq!(entry_param_count(FAKE_PTX, "missing"), None);
}
